// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhGj7RixQmDM95uKPEJup13h4cg-Uv824',
    appId: '1:718762511471:web:00b97f0000a4a66c69919a',
    messagingSenderId: '718762511471',
    projectId: 'vehicle-care-1148f',
    authDomain: 'vehicle-care-1148f.firebaseapp.com',
    storageBucket: 'vehicle-care-1148f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD58Sx760gbVDFE5_mUEL7ixZYFCf_G0Bc',
    appId: '1:718762511471:android:54db415c8dd195c169919a',
    messagingSenderId: '718762511471',
    projectId: 'vehicle-care-1148f',
    storageBucket: 'vehicle-care-1148f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQmVaBUYH4pmSpchpU-Wkh159Nmq1prZg',
    appId: '1:718762511471:ios:899bc141e4a5920069919a',
    messagingSenderId: '718762511471',
    projectId: 'vehicle-care-1148f',
    storageBucket: 'vehicle-care-1148f.firebasestorage.app',
    androidClientId:
        '718762511471-5thdout77han6l9ro6sq9hc48gj39mav.apps.googleusercontent.com',
    iosClientId:
        '718762511471-9o15l2m3420abpbf437tpr8bne3s94mb.apps.googleusercontent.com',
    iosBundleId: 'com.vehiclecare.vehicleCare',
  );
}
