/// Arabic (default) string table.
const Map<String, String> kStringsAr = {
  // App shell
  'appTitle': 'العناية بالسيارة',
  'tabHome': 'الرئيسية',
  'tabMaintenanceLog': 'سجل الصيانة',
  'tabSchedule': 'جدول الصيانات',
  'tabFuel': 'الوقود',
  'tabExpenses': 'المصاريف',
  'tabWorkshops': 'الورش',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'themeMode': 'المظهر',
  'themeSystem': 'حسب النظام',
  'themeLight': 'فاتح',
  'themeDark': 'داكن',
  'notifications': 'التنبيهات',

  // Generic
  'save': 'حفظ',
  'cancel': 'إلغاء',
  'delete': 'حذف',
  'edit': 'تعديل',
  'add': 'إضافة',
  'search': 'بحث',
  'all': 'الكل',
  'none': 'لا يوجد',
  'today': 'اليوم',
  'date': 'التاريخ',
  'notes': 'ملاحظات',
  'optional': 'اختياري',
  'required': 'هذا الحقل مطلوب',
  'invalidNumber': 'أدخل رقمًا صحيحًا',
  'km': 'كم',
  'liter': 'لتر',
  'cubicMeter': 'م³',
  'currency': 'ج.م',
  'perKm': 'لكل كم',
  'lPer100Km': 'ل/100كم',
  'metricLPer100Km': 'لتر / 100 كم',
  'metricKmPerLiter': 'كيلومتر / لتر',
  'fuelEconomy': 'اقتصاد الوقود',
  'currentTank': 'الخزان الحالي',
  'runningCostPerKm': 'التكلفة الجارية / كم',
  'sinceLastFill': 'منذ آخر تعبئة',
  'liveConsumption': 'لحظي',
  'settledConsumption': 'مستقر',
  'displayMetric': 'وحدة الكفاءة',
  'defaultFuelPrice': 'سعر اللتر الافتراضي',
  'defaultFuelPriceHint': 'يُعبأ تلقائياً لهذا النوع عند إضافة تعبئة جديدة',
  'onThisTank': 'على هذا الخزان',
  'amortising': 'تنخفض كلما قدت',
  'ecoTips': 'القيادة الاقتصادية وتوفير الوقود',
  'ecoTipsHint': 'عادات صغيرة، لترات محسوسة',
  'ecoCatDriving': 'عادات القيادة',
  'ecoCatClimate': 'التكييف',
  'ecoCatVehicle': 'السيارة والصيانة',
  'ecoDriving1': 'انطلق بسلاسة',
  'ecoDriving1Body':
      'اضغط دواسة البنزين بهدوء بدل الانطلاق المفاجئ. التسارع العنيف قد يستهلك وقوداً أكثر بنحو الثلث على نفس المسافة.',
  'ecoDriving2': 'حافظ على سرعة ثابتة',
  'ecoDriving2Body':
      'السرعة الثابتة أوفر بكثير من التسارع والتباطؤ المتكرر. على الطرق المفتوحة أغلب السيارات أكفأ بين 80 و100 كم/س.',
  'ecoDriving3': 'فرمل مبكراً وبهدوء',
  'ecoDriving3Body':
      'راقب الطريق أمامك وارفع قدمك مبكراً. كل فرملة عنيفة تهدر سرعة دفعت وقوداً بالفعل للوصول إليها.',
  'ecoClimate1': 'صرّف هواء الكابينة أولاً',
  'ecoClimate1Body':
      'افتح النوافذ أول دقيقة لإخراج الهواء الساخن، ثم أغلقها وشغّل التكييف. الكمبروسور سيعمل بجهد أقل بكثير.',
  'ecoClimate2': 'استخدم إعادة تدوير الهواء',
  'ecoClimate2Body':
      'بعد أن تبرد الكابينة حوّل إلى وضع إعادة التدوير. تبريد هواء الداخل أرخص كثيراً من تبريد الهواء الخارجي الساخن مراراً.',
  'ecoClimate3': 'النوافذ داخل المدينة، والتكييف على الطريق السريع',
  'ecoClimate3Body':
      'تحت 60 كم/س تقريباً تكون النوافذ المفتوحة أوفر من التكييف. وفوق ذلك تصبح مقاومة الهواء أغلى من الكمبروسور.',
  'ecoVehicle1': 'افحص ضغط الإطارات شهرياً',
  'ecoVehicle1Body':
      'الإطارات الناقصة تزيد المقاومة. نقص 10% قد يكلفك نحو 2% من الوقود ويستهلك جوانب الإطار مبكراً.',
  'ecoVehicle2': 'أطفئ المحرك بدل التشغيل على الفاضي',
  'ecoVehicle2Body':
      'الوقوف بالمحرك دائراً أكثر من 30 ثانية يستهلك أكثر من إعادة التشغيل. عند إشارة طويلة أو مزلقان، أطفئ المحرك.',
  'ecoVehicle3': 'أفرغ الشنطة',
  'ecoVehicle3Body':
      'كل 50 كجم وزن زائد تكلف نحو 1% إلى 2% من الوقود. وحمّالات السقف أغلى بكثير — انزعها عند عدم الحاجة.',
  'close': 'إغلاق',
  'pressBackToExit': 'اضغط مرة أخرى للخروج',
  'customItems': 'بنود أخرى',
  'viewReplacedParts': 'عرض الأجزاء المستبدلة',
  'noPartsRecorded': 'لم تُسجَّل أجزاء أو فحوصات لهذه الصيانة.',
  'partsCount': 'أجزاء',
  'exportPdfHint': 'تقرير منسّق يحتوي جداول ملخّصة ورسوم بيانية للاتجاهات.',
  'exportDataHint': 'بيانات خام للجداول الحسابية والنسخ الاحتياطية.',
  'allPartsHealthy': 'كل الأجزاء سليمة',
  'initialOdometerHint':
      'القراءة اللي انضمت بيها العربية للتطبيق. كل حسابات التكلفة لكل كم بتتقاس منها.',
  'initialAboveCurrent': 'لا يمكن أن تكون أكبر من القراءة الحالية',
  'editFuelEntry': 'تعديل تعبئة الوقود',
  'editService': 'تعديل الصيانة',
  'editExpense': 'تعديل المصروف',
  'editWorkshop': 'تعديل الورشة',
  'saveChanges': 'حفظ التعديلات',
  'currentOdometerHint': 'لا تقل عن القراءة الابتدائية',
  'odometerRequired': 'مطلوب',
  'fuelEmergency': 'نفاد الوقود',
  'fuelEmergencyHint': 'اعمل إيه لما البنزين يخلص',
  'fuelEmgCatSafety': 'أمّن العربية',
  'fuelEmgCatEngine': 'احمِ المحرك',
  'fuelEmgCatRefuel': 'إعادة التزود',
  'fuelEmg1': 'اخرج على جانب الطريق',
  'fuelEmg1Body':
      'أول ما تحس المحرك بدأ يفصل، استغل سرعة العربية للوصول لجانب الطريق. الدركسيون والفرامل بيتقلوا بعد ما المحرك يقف، فقرر بدري بدل ما تقف في نص الطريق.',
  'fuelEmg2': 'شغّل الفلاشر فوراً',
  'fuelEmg2Body':
      'شغّل الفلاشر قبل ما تقف مش بعدها. بالليل أو في المطر شغّل النور الجانبي كمان عشان العربية تبان من مسافة.',
  'fuelEmg3': 'حُط المثلث العاكس',
  'fuelEmg3Body':
      'ضع المثلث العاكس على مسافة كافية خلف العربية، وأبعد على الطرق السريعة، والبس السترة العاكسة. استنى خلف الحاجز، مش جوه العربية على جانب طريق سريع.',
  'fuelEmg4': 'بطّل تدوير المارش',
  'fuelEmg4Body':
      'المحاولات المتكررة والتانك فاضي بتسخّن المارش وممكن تحرقه. محاولتين قصيرين كفاية إنك تتأكد من المشكلة.',
  'fuelEmg5': 'متشغّلش طرمبة البنزين على الفاضي',
  'fuelEmg5Body':
      'طرمبة البنزين بتتبرّد وتتزيّت بالبنزين اللي حواليها. اقفل الكونتاكت وسيبه مقفول. اللي بيحرق الطرمبة هو تشغيلها فاضية، مش التانك الفاضي نفسه.',
  'fuelEmg6': 'الديزل محتاج تطريد هوا',
  'fuelEmg6Body':
      'موتور الديزل لما يخلص سولار بيسحب هوا في المواسير ومش هيدور بالوقود لوحده. هتحتاج تطرد الهوا من المنظومة، ولو مفيش طرمبة تطريد يدوية كلّم فني.',
  'fuelEmg7': 'استخدم جركن معتمد بس',
  'fuelEmg7Body':
      'اشترِ جركن وقود معتمد حديد أو بلاستيك. متستخدمش أبداً زجاجة مياه أو عبوة زيت: بتذوب وبتسرّب وبتولّد كهربا ساكنة. املأه وهو على الأرض، مش في الشنطة أو على سطح بلاستيك.',
  'fuelEmg8': 'اتأكد من نوع البنزين قبل ما تصب',
  'fuelEmg8Body':
      'اتأكد من رقم الأوكتان اللي عربيتك بتاخده، أو إنها ديزل، قبل ما تملأ الجركن. الغلط في النوع هيكلفك أضعاف الونش اللي كنت بتوفره. لو مش متأكد، متشغّلش المحرك واطلب مساعدة.',
  'fuelEmg9': 'صُب كمية كافية وشغّل صح',
  'fuelEmg9Body':
      'من 5 لـ10 لتر كفاية توصلك لأقرب محطة. لِف الكونتاكت على ON كام ثانية من غير تدوير عشان الطرمبة تضغط، بعدين شغّل. املأ التانك بالكامل في أول محطة ومتوصّلش لنقطة الفاضي تاني.',
  'fuelGuidelines': 'استهلاك الوقود والكفاءة',
  'fuelGuidelinesHint': 'وفّر أكتر، واعرف لما يبقى فيه مشكلة',
  'fuelGuideCatDriving': 'عادات القيادة',
  'fuelGuideCatMaintenance': 'فحوصات الصيانة',
  'fuelGuideCatLoad': 'الوزن ومقاومة الهواء',
  'fuelGuide1': 'انطلق بسلاسة',
  'fuelGuide1Body':
      'اضغط دواسة البنزين بهدوء بدل الانطلاق المفاجئ. التسارع العنيف قد يستهلك وقوداً أكثر بنحو الثلث على نفس المسافة.',
  'fuelGuide2': 'حافظ على سرعة ثابتة',
  'fuelGuide2Body':
      'السرعة الثابتة أوفر بكثير من التسارع والتباطؤ المتكرر. على الطرق المفتوحة أغلب السيارات أكفأ بين 80 و100 كم/س.',
  'fuelGuide3': 'استخدم فرملة المحرك',
  'fuelGuide3Body':
      'ارفع رجلك بدري وسيب العربية تبطّأ وهي على السرعة. الحقن الحديث بيقطع البنزين تماماً وقتها، فالتباطؤ على السرعة مجاني، بينما النيوترال بيفضل يستهلك.',
  'fuelGuide4': 'افحص ضغط الإطارات شهرياً',
  'fuelGuide4Body':
      'الإطارات الناقصة تزيد المقاومة. نقص 10% قد يكلفك نحو 2% من الوقود ويستهلك جوانب الإطار مبكراً.',
  'fuelGuide5': 'غيّر الفلاتر المسدودة',
  'fuelGuide5Body':
      'فلتر الهواء المسدود بيخنق المحرك، وفلتر البنزين المتعب بيحمّل الطرمبة. الاتنين بيظهروا كارتفاع تدريجي غير مفهوم في الاستهلاك.',
  'fuelGuide6': 'افحص البوچيهات والبخاخات',
  'fuelGuide6Body':
      'البوچيهات المستهلكة والبخاخات المتسخة بتحرق بنزين من غير ما تحوّله لحركة. القفزة المفاجئة في الاستهلاك مع رعشة في الرالنتي أو تردد في السحب بتشاور على دول الأول.',
  'fuelGuide7': 'فضّي الشنطة',
  'fuelGuide7Body':
      'كل 50 كجم وزن زائد تكلف نحو 1% إلى 2% من الوقود. شيل اللي قاعد فيها من شهور من غير سبب.',
  'fuelGuide8': 'انزع حمّالة السقف',
  'fuelGuide8Body':
      'حمّالة السقف أو الصندوق حتى وهو فاضي ممكن يكلفك أكتر من 10% على الطريق السريع. انزعه يوم ما الرحلة تخلص، مش لما تحتاجه تاني.',
  'fuelGuide9': 'اقفل الشبابيك على السرعات العالية',
  'fuelGuide9Body':
      'فوق 60 كم/س تقريباً الشبابيك المفتوحة بتكلف في مقاومة الهواء أكتر من التكييف. وتحت كده الشبابيك هي الأوفر.',
  'appTagline': 'كل صيانة، كل لتر، كل كيلومتر',
  'splashPreparing': 'بنجهّز جراجك',
  'notifServiceKmTitle': 'الصيانة قربت',
  'alertServiceKmRemaining': 'صيانة {km} كم · باقي {remaining} كم',
  'alertPartKmRemaining': '{part} · باقي {remaining} كم',
  'kmPerLiter': 'كم/لتر',
  'day': 'يوم',
  'days': 'يوم',
  'month': 'شهر',
  'months': 'أشهر',
  'viewAll': 'عرض الكل',
  'confirmDelete': 'هل تريد حذف هذا العنصر؟',
  'retry': 'إعادة المحاولة',
  'somethingWentWrong': 'حدث خطأ ما',

  // Vehicles
  'vehicles': 'السيارات',
  'myVehicles': 'سياراتي',
  'addVehicle': 'إضافة سيارة',
  'editVehicle': 'تعديل السيارة',
  'make': 'الماركة',
  'model': 'الموديل',
  'year': 'سنة الصنع',
  'nickname': 'اسم مختصر',
  'plateNumber': 'رقم اللوحة',
  'otherOption': 'أخرى',
  'searchCatalog': 'بحث',
  'noCatalogMatches': 'لا توجد نتائج مطابقة',
  'selectMakeFirst': 'اختر الماركة أولاً',
  'customMake': 'ماركة أخرى',
  'customModel': 'موديل آخر',
  'tankCapacity': 'سعة خزان الوقود',
  'initialOdometer': 'قراءة العداد الابتدائية',
  'currentOdometer': 'قراءة العداد',
  'vehicleCurrentOdometer': 'قراءة العداد الحالية',
  'updateOdometer': 'تحديث العداد',
  'purchaseDate': 'تاريخ الشراء',
  'licenseExpiry': 'انتهاء الرخصة',
  'insuranceExpiry': 'انتهاء التأمين',
  'noVehicles': 'لا توجد سيارات بعد',
  'noVehiclesHint': 'أضف سيارتك الأولى لتبدأ تتبع الصيانة والوقود',
  'switchVehicle': 'تبديل السيارة',

  // Dashboard
  'dashboard': 'لوحة التحكم',
  'totalSpend': 'إجمالي المصروفات',
  'thisMonth': 'هذا الشهر',
  'avgDaily': 'متوسط يومي',
  'avgMonthly': 'متوسط شهري',
  'alerts': 'تنبيهات',
  'noAlerts': 'كل شيء تمام، لا توجد تنبيهات',
  'consumablesHealth': 'حالة الأجزاء المستهلكة',
  'documents': 'التأمين والوثائق',
  'carInsurance': 'تأمين السيارة',
  'carLicense': 'رخصة السيارة',
  'renewsOn': 'يجدد في',
  'remainingDays': 'متبقي {n} يوم',
  'expired': 'منتهي',
  'fuelEfficiency': 'كفاءة الوقود',
  'quickActions': 'إجراءات سريعة',
  'lifespan': 'العمر الافتراضي',
  'consumed': 'تم استهلاك',
  'remaining': 'متبقي',
  'overdue': 'متأخرة',
  'dueSoon': 'قريبة',
  'healthy': 'جيدة',

  // Fuel
  'fuelLogs': 'سجل الوقود',
  'addFuelEntry': 'إضافة تعبئة وقود',
  'fuelType': 'نوع الوقود',
  'fuelAmount': 'الكمية (لتر)',
  'fuelAmountGas': 'الكمية (م³)',
  'totalCost': 'التكلفة الإجمالية',
  'pricePerLiter': 'سعر اللتر',
  'pricePerCubicMeter': 'سعر المتر المكعب',
  'fullTank': 'تعبئة كاملة',
  'fullTankHint': 'اختياري. التعبئة الجزئية تُحتسب أيضاً',
  'efficiency': 'الكفاءة',
  'costPerKm': 'التكلفة لكل كم',
  'distance': 'المسافة',
  'bestEfficiency': 'أفضل كفاءة',
  'avgEfficiency': 'متوسط الكفاءة',
  'octaneComparison': 'مقارنة أنواع البنزين',
  'octaneComparisonHint': 'متوسط الكفاءة والتكلفة لكل نوع وقود استخدمته',
  'noFuelLogs': 'لا يوجد سجل وقود بعد',
  'needsTwoFills': 'يحتاج تعبئة ثانية لحساب الاستهلاك',
  'octane80': 'بنزين ٨٠',
  'octane92': 'بنزين ٩٢',
  'octane95': 'بنزين ٩٥',
  'diesel': 'سولار',
  'naturalGas': 'غاز طبيعي',
  'fuelTrend': 'تطور الكفاءة',

  // Maintenance
  'maintenance': 'الصيانة',
  'maintenanceHistory': 'سجل الصيانات',
  'logService': 'تسجيل صيانة',
  'serviceType': 'نوع الصيانة',
  'workshop': 'الورشة',
  'cost': 'التكلفة',
  'partsReplaced': 'الأجزاء المستبدلة',
  'consumableParts': 'قطع الغيار',
  'trackedDistance': 'المسافة المتتبعة',
  'costPerKmHint': 'إجمالي الإنفاق على المسافة المقطوعة منذ إضافة السيارة',
  'noDistanceYet': 'قُد المسافة لعرض التكلفة لكل كم',
  'replaceAndChange': 'تغيير و استبدال',
  'inspectAndReview': 'فحص ومراجعة',
  'majorService': 'صيانة كبرى',
  'minorService': 'صيانة صغرى',
  'importantService': 'صيانة هامة',
  'nextService': 'الصيانة القادمة',
  'estimatedDate': 'التاريخ المتوقع',
  'upcomingServices': 'الصيانات القادمة',
  'completedServices': 'الصيانات المنفذة',
  'serviceRoadmap': 'خريطة الصيانات',
  'noMaintenanceLogs': 'لا يوجد سجل صيانة بعد',
  'markDone': 'تم التنفيذ',
  'resetPart': 'تصفير الجزء',
  'resetPartHint': 'سجّل استبدال هذا الجزء عند العداد الحالي',

  // Expenses
  'expenses': 'المصاريف',
  'addExpense': 'إضافة مصروف',
  'category': 'التصنيف',
  'amount': 'المبلغ',
  'title': 'البيان',
  'noExpenses': 'لا توجد مصاريف مسجلة',
  'breakdown': 'التوزيع',
  'catRepair': 'إصلاحات',
  'catAccessories': 'إكسسوارات',
  'catParking': 'انتظار',
  'catFines': 'مخالفات',
  'catWash': 'غسيل',
  'catTolls': 'رسوم طرق',
  'catInsurance': 'تأمين',
  'catLicense': 'رخص',
  'catOther': 'أخرى',

  // Dealers & emergency
  'workshopsAndDealers': 'الورش والموزعين',
  'authorizedDealers': 'الوكلاء المعتمدون',
  'addWorkshop': 'إضافة ورشة',
  'searchDealers': 'ابحث بالاسم أو المدينة',
  'call': 'اتصال',
  'hotline': 'الخط الساخن',
  'openInMaps': 'فتح في الخرائط',
  'openingHours': 'مواعيد العمل',
  'rating': 'التقييم',
  'city': 'المدينة',
  'address': 'العنوان',
  'phone': 'الهاتف',
  'services': 'الخدمات',
  'noDealers': 'لا توجد نتائج مطابقة',
  'emergency': 'الطوارئ',
  'emergencyNumbers': 'أرقام الطوارئ',
  'safetyTips': 'إرشادات السلامة على الطريق',
  'couldNotLaunch': 'تعذر تنفيذ الإجراء على هذا الجهاز',

  // Consumable parts
  'partEngineOil': 'زيت المحرك',
  'partOilFilter': 'فلتر الزيت',
  'partAirFilter': 'فلتر هواء المحرك',
  'partCabinFilter': 'فلتر التكييف',
  'partBrakePads': 'تيل الفرامل',
  'partBrakeFluid': 'زيت الفرامل',
  'partTires': 'الإطارات (الكاوتش)',
  'partTransmissionOil': 'زيت الفتيس',
  'partPowerSteering': 'زيت الباور',
  'partCoolant': 'مياه التبريد',
  'partSparkPlugs': 'البوجيهات',
  'partBattery': 'البطارية',

  // Inspection checklist
  'checkTires': 'الإطارات وضغط الهواء',
  'checkSuspension': 'العفشة',
  'checkTightening': 'تربيط كامل',
  'checkLights': 'الإضاءة والإشارات',
  'checkRearPads': 'تيل الفرامل الخلفي',
  'checkCoolingCircuit': 'مراجعة دورة التبريد',
  'checkBattery': 'فحص البطارية',

  // Dealer kinds & services
  'kindAuthorizedService': 'مركز خدمة معتمد',
  'kindSpecializedCenter': 'مركز خدمة متخصص',
  'kindShowroom': 'معرض',
  'kindWorkshop': 'ورشة',
  'kindTireShop': 'مركز إطارات',
  'kindTowing': 'ونش وإنقاذ',
  'srvPeriodic': 'صيانة دورية',
  'srvMechanical': 'ميكانيكا',
  'srvElectrical': 'كهرباء',
  'srvBodyPaint': 'سمكرة ودهان',
  'srvSpareParts': 'قطع غيار',
  'srvSales': 'مبيعات',

  // Emergency
  'emPolice': 'الشرطة',
  'emAmbulance': 'الإسعاف',
  'emFire': 'المطافئ',
  'emTraffic': 'المرور',
  'emTourist': 'شرطة السياحة',
  'emGas': 'طوارئ الغاز',
  'emElectricity': 'طوارئ الكهرباء',

  // Safety tips
  'tipHazardLights': 'شغّل فلاشر التحذير فورًا عند التوقف الاضطراري.',
  'tipPullOverRight': 'اخرج بالسيارة إلى أقصى اليمين بعيدًا عن مسار السير.',
  'tipTriangle': 'ضع المثلث العاكس على بعد ٥٠-١٠٠ متر خلف السيارة.',
  'tipExitFromRight': 'انزل من الباب الأيمن دائمًا، لا تنزل ناحية الطريق.',
  'tipStayBehindBarrier': 'انتظر خلف الحاجز أو بعيدًا عن السيارة، لا بداخلها.',
  'tipShareLocation': 'شارك موقعك الحي مع شخص تثق به قبل طلب المساعدة.',
  'tipKeepKit': 'احتفظ دائمًا بمثلث، إسطبانة، كابل بطارية وطفاية حريق.',

  // Extra UI
  'addFirstEntry': 'ابدأ بإضافة أول عملية',
  'partialFill': 'تعبئة جزئية',
  'estimated': 'تقديري',
  'basedOnYourDriving': 'بناءً على متوسط قيادتك',
  'notEnoughData': 'لا توجد بيانات كافية بعد',
  'litersShort': 'ل',
  'perLiter': 'للتر',
  'segmentSince': 'منذ آخر تعبئة كاملة',
  'daysShort': 'ي',
  'noSchedule': 'أضف قراءة العداد لعرض الجدول',
  'kmRemainingLabel': 'باقي {n} كم',
  'kmOverdueLabel': 'متأخرة بـ {n} كم',
  'serviceAt': 'عند {n} كم',
  'monthsLabel': '{n} شهر',
  'done': 'تمت',
  'vsAverage': 'مقارنة بالمتوسط',
  'better': 'أفضل',
  'worse': 'أقل',
  'addNote': 'أضف ملاحظة',
  'chooseParts': 'اختر الأجزاء التي تم تغييرها',
  'stationName': 'اسم المحطة',
  'rateThisPlace': 'قيّم هذا المكان',
  'thanksForRating': 'شكرًا لتقييمك',
  'deleted': 'تم الحذف',
  'saved': 'تم الحفظ',

  // Alerts & notifications
  'alertServiceOverdue': 'صيانة {km} كم متأخرة',
  'alertServiceDueSoon': 'اقتربت صيانة {km} كم',
  'alertPartOverdue': '{part} تجاوز عمره الافتراضي',
  'alertPartDueSoon': '{part} يحتاج استبدال قريبًا',
  'alertLicenseExpired': 'رخصة السيارة منتهية',
  'alertLicenseExpiring': 'رخصة السيارة تنتهي خلال {n} يوم',
  'alertInsuranceExpired': 'تأمين السيارة منتهي',
  'alertInsuranceExpiring': 'تأمين السيارة ينتهي خلال {n} يوم',
  'alertOdometerStale': 'حدّث قراءة العداد',
  'alertOdometerStaleDetail':
      'آخر تحديث من {n} يوم — التحديث يحسّن دقة التوقعات',
  'notifServiceTitle': 'موعد صيانة قادم',
  'notifPartTitle': 'جزء يحتاج استبدال',
  'notifDocumentTitle': 'تجديد وثيقة',

  // Analytics & export
  'analytics': 'التحليلات',
  'dateRange': 'الفترة الزمنية',
  'rangeLast3Months': '٣ أشهر',
  'rangeLast6Months': '٦ أشهر',
  'rangeLastYear': 'سنة',
  'rangeAllTime': 'كل الفترات',
  'customRange': 'فترة مخصصة',
  'exportReport': 'تصدير التقرير',
  'exportFormat': 'صيغة الملف',
  'exportNow': 'تصدير الآن',
  'exportSavedTo': 'تم الحفظ في',
  'exportDownloaded': 'بدأ تنزيل الملف',
  'exportFailed': 'تعذر تصدير التقرير',
  'entries': 'عدد العمليات',
  'reportSummary': 'ملخص التقرير',
  'totalDistance': 'إجمالي المسافة',
  'totalLiters': 'إجمالي اللترات',

  // نسخ بيانات السيارة — ملف واحد لكل سيارة يحمل تاريخها بالكامل
  'vehicleTransfer': 'نسخة بيانات السيارة',
  'vehicleTransferHint':
      'ملف النسخة يحتوي سيارة واحدة مع صياناتها وتعبئات الوقود والمصروفات '
      'ومواعيد التجديد. الاستيراد يضيفها كسيارة جديدة ولا يستبدل أي سيارة '
      'موجودة.',
  'exportVehicle': 'تصدير السيارة',
  'importVehicle': 'استيراد ملف سيارة',
  'vehicleExportFailed': 'تعذر تصدير بيانات هذه السيارة',
  'vehicleImported': 'تم استيراد {name} · {n} عملية',
  'importFailed': 'تعذر استيراد هذا الملف',
  'importWrongFormat': 'هذا الملف ليس نسخة بيانات سيارة',
  'importUnsupportedVersion': 'هذه النسخة أُنشئت بإصدار أحدث من التطبيق',

  // Maintenance engine
  'firstCheckService': 'فحص أول (تشغيل)',
  'nextServiceDue': 'موعد الصيانة القادمة',
  'sinceLastService': 'منذ آخر صيانة',
  'basedOnLastService': 'محسوبة من آخر صيانة عند {n} كم',
  'noServiceYet': 'لم تسجل أي صيانة بعد',
  'dueByDistance': 'حسب المسافة',
  'dueByTime': 'حسب المدة',
  'firstCheckHint': 'أول ١٠٠٠ كم أو بعد شهر من الاستلام',

  // Backend
  'dataSource': 'مصدر البيانات',
  'sourceLocal': 'محلي',
  'sourceCloud': 'سحابي',
  'sourceLocalHint': 'كل البيانات محفوظة على الجهاز فقط',
  'sourceCloudHint': 'مزامنة حية مع النسخ الاحتياطي السحابي',
  'cloudUnavailable': 'خدمة النسخ الاحتياطي السحابي غير متوفرة حالياً',

  // Vehicle paint
  'vehicleColor': 'لون السيارة',
  'paintBlack': 'أسود',
  'paintWhite': 'أبيض',
  'paintSilver': 'فضي / رمادي',
  'paintNavy': 'كحلي',
  'paintRed': 'أحمر',
  'paintOlive': 'زيتي',
  'paintBronze': 'برونزي / بني',
  'addVehicleToView': 'أضف سيارة للعرض',

  // Vehicle photo
  'vehiclePhoto': 'صورة السيارة',
  'takePhoto': 'التقاط صورة',
  'chooseFromGallery': 'اختيار من المعرض',
  'uploadImage': 'رفع صورة',
  'removePhoto': 'إزالة الصورة',
  'imageTooLarge': 'الصورة كبيرة جدًا، اختر صورة أصغر',

  // Schedule & pricing
  'partFuelFilter': 'فلتر البنزين',
  'partDrainPlugGasket': 'جوان مسمار الزيت',
  'partTransmissionFilter': 'فلتر الفتيس',
  'partTimingBelt': 'سير الكاتينة والشداد',
  'partDriveBelt': 'سير الماكينة',
  'itemCleanerSupplies': 'مواد تنظيف ومستلزمات',
  'checkFluidLevels': 'فحص مستويات السوائل',
  'checkChassisScan': 'فحص عام للشاسيه',
  'checkLeaks': 'فحص التسريبات',
  'freeService': 'مجانية',
  'estimatedCost': 'التكلفة التقديرية',
  'priceSettings': 'إعدادات الأسعار',
  'priceMultiplier': 'معامل الأسعار',
  'priceMultiplierHint': 'اضبط الأسعار حسب أسعار السوق لديك',
  'customPrice': 'سعر مخصص',
  'resetPrices': 'إعادة الأسعار الافتراضية',
  'optionalExtras': 'إضافات اختيارية',
  'labourCost': 'المصنعية',
  'priceRangeNote': 'تقديري — قد يختلف حسب الورشة',

  // Predictive forecast
  'forecastTitle': 'التوقعات',
  'forecastNeedDataTitle': 'لا توجد بيانات كافية بعد',
  'forecastNeedDataHint':
      'سجّل قراءتين للعداد أو تعبئتين للوقود على الأقل حتى يُحسب المعدل اليومي.',
  'forecastHabits': 'عادات القيادة',
  'forecastAvgDaily': 'متوسط المسافة اليومية',
  'forecastPerDay': 'يوم',
  'forecastMonthlyKm': 'المسافة المتوقعة شهرياً',
  'forecastYearlyKm': 'المسافة المتوقعة سنوياً',
  'forecastDates': 'تواريخ الصيانة المتوقعة',
  'forecastNoUpcoming': 'لا توجد صيانات قادمة لتقدير موعدها من هذا المعدل.',
  'forecastSpend': 'توقع الوقود والمصروفات',
  'forecastTotal': 'إجمالي الإنفاق المتوقع',
  'parkingTitle': 'مكان ركن السيارة',
  'parkingSave': 'احفظ مكان الركن',
  'parkingUpdate': 'تعديل التفاصيل',
  'parkingSaved': 'تم حفظ مكان الركن',
  'parkingCleared': 'تم مسح مكان الركن',
  'parkingFound': 'وصلت للسيارة',
  'parkingDirections': 'الاتجاهات إلى السيارة',
  'parkingFloorLabel': 'الدور / المنطقة / القطعة',
  'parkingFloorHint': 'جراج روكسي - دور -٢ قطعة B14',
  'parkingNoteLabel': 'ملاحظة',
  'parkingNoteHint': 'جنب الأسانسير، عمود أزرق',
  'parkingEmptyHint': 'حدّد مكان ركنك عشان توصل للسيارة بسهولة بعدين.',
  'parkingParkedAt': 'وقت الركن',
  'parkingLocating': 'جارٍ تحديد موقعك…',
  'parkingNoFix': 'لم يتم تحديد الموقع بعد — التفاصيل اللي كتبتها محفوظة.',
  'parkingErrService': 'خدمة الموقع مقفولة على الجهاز. شغّلها وحاول تاني.',
  'parkingErrDenied': 'التطبيق محتاج إذن الموقع عشان يحفظ مكان الركن.',
  'parkingErrForever': 'إذن الموقع محظور. افتح الإعدادات للسماح به.',
  'parkingErrUnavailable': 'تعذّر تحديد الموقع. جرّب تاني في مكان مكشوف.',
  'parkingOpenSettings': 'فتح الإعدادات',
  'or': 'أو',
  'authTitle': 'حسابك',
  'authSubtitle': 'سجّل الدخول عشان بياناتك تفضل معاك على أي جهاز.',
  'authSignIn': 'تسجيل الدخول',
  'authSignUp': 'إنشاء حساب',
  'authSignOut': 'تسجيل الخروج',
  'authGoogle': 'المتابعة بحساب Google',
  'authSkip': 'المتابعة بدون حساب',
  'authEmail': 'البريد الإلكتروني',
  'authPassword': 'كلمة المرور',
  'authName': 'الاسم',
  'authHaveAccount': 'عندك حساب؟ سجّل الدخول',
  'authNeedAccount': 'معندكش حساب؟ أنشئ حساب',
  'authForgot': 'نسيت كلمة المرور؟',
  'authResetSent': 'تم إرسال رسالة إعادة تعيين كلمة المرور',
  'authLocalOnly': 'الشغل على الجهاز ده بس',
  'authLocalOnlyHint':
      'بياناتك محفوظة هنا. سجّل الدخول عشان تتخزن وتوصلها من جهاز تاني.',
  'authSignedInAs': 'مسجّل الدخول باسم',
  'authAnonymous': 'حساب ضيف',
  'authAnonymousHint':
      'بياناتك بتتزامن، بس هتضيع لو التطبيق اتشال. ضيف بريد إلكتروني عشان '
      'تحتفظ بيها.',
  'authSignOutConfirm': 'تسجيل الخروج؟ بياناتك في السحابة هتفضل في حسابك.',
  'authErrInvalidEmail': 'البريد الإلكتروني ده شكله مش مظبوط.',
  'authErrWrongPassword': 'البريد أو كلمة المرور غلط.',
  'authErrUserNotFound': 'مفيش حساب بالبريد ده.',
  'authErrEmailInUse': 'فيه حساب مستخدم البريد ده بالفعل.',
  'authErrWeakPassword': 'اختار كلمة مرور أطول — ٦ حروف على الأقل.',
  'authErrNetwork': 'مفيش اتصال. حاول تاني لما النت يرجع.',
  'authErrNotConfigured': 'المزامنة السحابية مش مفعّلة في النسخة دي.',
  'authErrUnknown': 'تعذّر تسجيل الدخول. حاول تاني.',
  'syncMigrating': 'جارٍ نقل بياناتك لحسابك…',
  'syncMigrated': 'بياناتك بقت في حسابك',
  'syncMigrateFailed': 'تعذّر رفع كل حاجة. لسه موجودة على الجهاز.',
  'syncMerged': 'تمت إضافة {n} سجل من الجهاز ده لحسابك',
  'syncNothingNew': 'حسابك محدّث بالفعل',
  'syncConflicts':
      'فيه {n} سجل مختلف بين الجهاز ده وحسابك. تم الاحتفاظ بنسخة الحساب.',
  'syncCloudOn': 'متزامن مع حسابك',
  'syncCloudOff': 'على الجهاز ده بس',
  'reportTitle': 'تقرير السيارة',
  'reportTrackedDistance': 'المسافة المسجّلة',
  'reportFuelCost': 'تكلفة الوقود',
  'reportServiceCost': 'تكلفة الصيانة',
  'reportPartsCost': 'تكلفة قطع الغيار',
  'reportOtherCost': 'تكاليف أخرى',
  'reportTotalCost': 'التكلفة الإجمالية',
  'reportLitres': 'عدد اللترات',
  'reportConsumption': 'الاستهلاك لتر/100كم',
  'reportEfficiency': 'الكفاءة كم/لتر',
  'reportFuelCostPerKm': 'تكلفة الوقود لكل كم',
  'reportCostPerKm': 'التكلفة الإجمالية لكل كم',
  'reportGenerated': 'أُنشئ في',
  'reportParts': 'قطع الغيار',
  'reportOther': 'أخرى',
  'reportMetric': 'البند',
  'reportValue': 'القيمة',
  'reportType': 'النوع',
  'reportCategory': 'الفئة',
  'reportDescription': 'الوصف',
  'reportOdometer': 'العداد',
  'reportQuantity': 'الكمية',
  'reportSpendBreakdown': 'أين ذهبت المصروفات',
  'reportConsumptionTrend': 'اتجاه استهلاك الوقود',
  'reportCostTrend': 'اتجاه التكلفة لكل كيلومتر',
  'reportTransactions': 'الحركات',
  'reportForecast': 'توقعات الإنفاق والوقود',
  'reportPerMonth': 'شهرياً',
  'reportPerYear': 'سنوياً',
  'reportDailyPace': 'متوسط المسافة اليومية',
  'reportProjectedDistance': 'المسافة المتوقعة',
  'reportAmortisedNote':
      'التأمين والترخيص موزّعان على أشهر المدة التي يغطيها كل تجديد، '
      'وليسا محسوبين في شهر السداد وحده.',
  'reportPage': 'صفحة {n} من {total}',
  'reportRowFuel': 'وقود',
  'reportRowService': 'صيانة',
  'reportRowExpense': 'مصروف',
  'forecastPolicies': 'التأمين والترخيص',
  'forecastPoliciesHint': 'موزّع على أشهر المدة التي يغطيها كل تجديد',
  'forecastPerMonth': 'شهر',
  'forecastPerYear': 'سنة',
  'forecastGauges': 'العمر المتبقي للقطع',
  'forecastNoParts': 'لا توجد قطع استهلاكية لتوقع حالتها بعد.',
};
