/// English string table. Also acts as the fallback for missing translations.
const Map<String, String> kStringsEn = {
  // App shell
  'appTitle': 'Vehicle Care',
  'tabHome': 'Home',
  'tabMaintenanceLog': 'Service Log',
  'tabSchedule': 'Schedule',
  'tabFuel': 'Fuel',
  'tabExpenses': 'Expenses',
  'tabWorkshops': 'Workshops',
  'settings': 'Settings',
  'language': 'Language',
  'themeMode': 'Appearance',
  'themeSystem': 'System',
  'themeLight': 'Light',
  'themeDark': 'Dark',
  'notifications': 'Notifications',

  // Generic
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'add': 'Add',
  'search': 'Search',
  'all': 'All',
  'none': 'None',
  'today': 'Today',
  'date': 'Date',
  'notes': 'Notes',
  'optional': 'optional',
  'required': 'This field is required',
  'invalidNumber': 'Enter a valid number',
  'km': 'km',
  'liter': 'L',
  'currency': 'EGP',
  'perKm': 'per km',
  'kmPerLiter': 'km/L',
  'day': 'day',
  'days': 'days',
  'month': 'month',
  'months': 'months',
  'viewAll': 'View all',
  'confirmDelete': 'Delete this entry?',
  'retry': 'Retry',
  'somethingWentWrong': 'Something went wrong',

  // Vehicles
  'vehicles': 'Vehicles',
  'myVehicles': 'My vehicles',
  'addVehicle': 'Add vehicle',
  'editVehicle': 'Edit vehicle',
  'make': 'Make',
  'model': 'Model',
  'year': 'Year',
  'nickname': 'Nickname',
  'plateNumber': 'Plate number',
  'initialOdometer': 'Current odometer',
  'currentOdometer': 'Odometer',
  'updateOdometer': 'Update odometer',
  'purchaseDate': 'Purchase date',
  'licenseExpiry': 'License expiry',
  'insuranceExpiry': 'Insurance expiry',
  'noVehicles': 'No vehicles yet',
  'noVehiclesHint': 'Add your first vehicle to start tracking fuel and service',
  'switchVehicle': 'Switch vehicle',

  // Dashboard
  'dashboard': 'Dashboard',
  'totalSpend': 'Total spend',
  'thisMonth': 'This month',
  'avgDaily': 'Daily average',
  'avgMonthly': 'Monthly average',
  'alerts': 'Alerts',
  'noAlerts': 'All good — nothing needs attention',
  'consumablesHealth': 'Consumable parts health',
  'documents': 'Insurance & documents',
  'carInsurance': 'Car insurance',
  'carLicense': 'Car license',
  'renewsOn': 'Renews on',
  'remainingDays': '{n} days left',
  'expired': 'Expired',
  'fuelEfficiency': 'Fuel efficiency',
  'quickActions': 'Quick actions',
  'lifespan': 'Rated life',
  'consumed': 'Used',
  'remaining': 'left',
  'overdue': 'Overdue',
  'dueSoon': 'Due soon',
  'healthy': 'Healthy',

  // Fuel
  'fuelLogs': 'Fuel logs',
  'addFuelEntry': 'Add fuel entry',
  'fuelType': 'Fuel type',
  'fuelAmount': 'Amount (L)',
  'totalCost': 'Total cost',
  'pricePerLiter': 'Price per litre',
  'fullTank': 'Full tank',
  'fullTankHint': 'Full-tank fills give the most accurate consumption',
  'efficiency': 'Efficiency',
  'costPerKm': 'Cost per km',
  'distance': 'Distance',
  'bestEfficiency': 'Best efficiency',
  'avgEfficiency': 'Average efficiency',
  'octaneComparison': 'Octane comparison',
  'octaneComparisonHint': 'Average efficiency and cost for each fuel you used',
  'noFuelLogs': 'No fuel entries yet',
  'needsTwoFills': 'Needs two full-tank fills to compute consumption',
  'octane92': 'Octane 92',
  'octane95': 'Octane 95',
  'diesel': 'Diesel',
  'fuelTrend': 'Efficiency trend',

  // Maintenance
  'maintenance': 'Maintenance',
  'maintenanceHistory': 'Service history',
  'logService': 'Log a service',
  'serviceType': 'Service type',
  'workshop': 'Workshop',
  'cost': 'Cost',
  'partsReplaced': 'Parts replaced',
  'replaceAndChange': 'Replace & change',
  'inspectAndReview': 'Inspect & review',
  'majorService': 'Major service',
  'minorService': 'Minor service',
  'importantService': 'Important service',
  'nextService': 'Next service',
  'estimatedDate': 'Estimated date',
  'upcomingServices': 'Upcoming services',
  'completedServices': 'Completed services',
  'serviceRoadmap': 'Service roadmap',
  'noMaintenanceLogs': 'No service history yet',
  'markDone': 'Mark as done',
  'resetPart': 'Reset part',
  'resetPartHint': 'Record this part as replaced at the current odometer',

  // Expenses
  'expenses': 'Expenses',
  'addExpense': 'Add expense',
  'category': 'Category',
  'amount': 'Amount',
  'title': 'Title',
  'noExpenses': 'No expenses logged',
  'breakdown': 'Breakdown',
  'catRepair': 'Repairs',
  'catAccessories': 'Accessories',
  'catParking': 'Parking',
  'catFines': 'Fines',
  'catWash': 'Car wash',
  'catTolls': 'Tolls',
  'catInsurance': 'Insurance',
  'catLicense': 'License',
  'catOther': 'Other',

  // Dealers & emergency
  'workshopsAndDealers': 'Workshops & dealers',
  'authorizedDealers': 'Authorized dealers',
  'addWorkshop': 'Add workshop',
  'searchDealers': 'Search by name or city',
  'call': 'Call',
  'hotline': 'Hotline',
  'openInMaps': 'Open in Maps',
  'openingHours': 'Opening hours',
  'rating': 'Rating',
  'city': 'City',
  'address': 'Address',
  'phone': 'Phone',
  'services': 'Services',
  'noDealers': 'No matching results',
  'emergency': 'Emergency',
  'emergencyNumbers': 'Emergency numbers',
  'safetyTips': 'Roadside safety tips',
  'couldNotLaunch': 'Could not perform this action on your device',

  // Consumable parts
  'partEngineOil': 'Engine oil',
  'partOilFilter': 'Oil filter',
  'partAirFilter': 'Engine air filter',
  'partCabinFilter': 'Cabin / AC filter',
  'partBrakePads': 'Brake pads',
  'partBrakeFluid': 'Brake fluid',
  'partTires': 'Tires',
  'partTransmissionOil': 'Transmission oil',
  'partPowerSteering': 'Power steering fluid',
  'partCoolant': 'Coolant',
  'partSparkPlugs': 'Spark plugs',
  'partBattery': 'Battery',

  // Inspection checklist
  'checkTires': 'Tires and pressure',
  'checkSuspension': 'Suspension',
  'checkTightening': 'Full tightening',
  'checkLights': 'Lights and indicators',
  'checkRearPads': 'Rear brake pads',
  'checkCoolingCircuit': 'Cooling circuit',
  'checkBattery': 'Battery check',

  // Dealer kinds & services
  'kindAuthorizedService': 'Authorized service centre',
  'kindSpecializedCenter': 'Specialized service centre',
  'kindShowroom': 'Showroom',
  'kindWorkshop': 'Workshop',
  'kindTireShop': 'Tire centre',
  'kindTowing': 'Towing & recovery',
  'srvPeriodic': 'Periodic service',
  'srvMechanical': 'Mechanical',
  'srvElectrical': 'Electrical',
  'srvBodyPaint': 'Body & paint',
  'srvSpareParts': 'Spare parts',
  'srvSales': 'Sales',

  // Emergency
  'emPolice': 'Police',
  'emAmbulance': 'Ambulance',
  'emFire': 'Fire brigade',
  'emTraffic': 'Traffic police',
  'emTourist': 'Tourist police',
  'emGas': 'Gas emergency',
  'emElectricity': 'Electricity emergency',

  // Safety tips
  'tipHazardLights': 'Switch on hazard lights the moment you stop.',
  'tipPullOverRight': 'Pull as far right as possible, clear of moving traffic.',
  'tipTriangle': 'Place the warning triangle 50-100 m behind the car.',
  'tipExitFromRight': 'Always leave through the right-hand door, never towards traffic.',
  'tipStayBehindBarrier': 'Wait behind the barrier, away from the car — not inside it.',
  'tipShareLocation': 'Share your live location with someone you trust before calling for help.',
  'tipKeepKit': 'Keep a triangle, spare wheel, jump leads and an extinguisher on board.',

  // Extra UI
  'addFirstEntry': 'Add your first entry to get started',
  'partialFill': 'Partial fill',
  'estimated': 'Estimated',
  'basedOnYourDriving': 'Based on your driving average',
  'notEnoughData': 'Not enough data yet',
  'litersShort': 'L',
  'perLiter': 'per litre',
  'segmentSince': 'since last full tank',
  'daysShort': 'd',
  'noSchedule': 'Add an odometer reading to see the schedule',
  'kmRemainingLabel': '{n} km to go',
  'kmOverdueLabel': '{n} km overdue',
  'serviceAt': 'at {n} km',
  'monthsLabel': '{n} months',
  'done': 'Done',
  'vsAverage': 'vs average',
  'better': 'better',
  'worse': 'lower',
  'addNote': 'Add a note',
  'chooseParts': 'Select the parts that were replaced',
  'stationName': 'Station name',
  'rateThisPlace': 'Rate this place',
  'thanksForRating': 'Thanks for rating',
  'deleted': 'Deleted',
  'saved': 'Saved',

  // Alerts & notifications
  'alertServiceOverdue': '{km} km service is overdue',
  'alertServiceDueSoon': '{km} km service is coming up',
  'alertPartOverdue': '{part} has passed its rated life',
  'alertPartDueSoon': '{part} needs replacing soon',
  'alertLicenseExpired': 'Car license has expired',
  'alertLicenseExpiring': 'Car license expires in {n} days',
  'alertInsuranceExpired': 'Car insurance has expired',
  'alertInsuranceExpiring': 'Car insurance expires in {n} days',
  'alertOdometerStale': 'Update your odometer',
  'alertOdometerStaleDetail': 'Last updated {n} days ago — updating sharpens every projection',
  'notifServiceTitle': 'Service coming up',
  'notifPartTitle': 'Part needs replacing',
  'notifDocumentTitle': 'Document renewal',

  // Analytics & export
  'analytics': 'Analytics',
  'dateRange': 'Date range',
  'rangeLast3Months': '3 months',
  'rangeLast6Months': '6 months',
  'rangeLastYear': '1 year',
  'rangeAllTime': 'All time',
  'customRange': 'Custom range',
  'exportReport': 'Export report',
  'exportFormat': 'File format',
  'exportNow': 'Export now',
  'exportSavedTo': 'Saved to',
  'exportDownloaded': 'Download started',
  'exportFailed': 'Could not export the report',
  'entries': 'Entries',
  'reportSummary': 'Report summary',
  'totalDistance': 'Total distance',
  'totalLiters': 'Total litres',

  // Maintenance engine
  'firstCheckService': 'First (run-in) check',
  'nextServiceDue': 'Next service due',
  'sinceLastService': 'since last service',
  'basedOnLastService': 'Based on your last service at {n} km',
  'noServiceYet': 'No service logged yet',
  'dueByDistance': 'by distance',
  'dueByTime': 'by time',
  'firstCheckHint': 'First 1,000 km or one month after delivery',

  // Backend
  'dataSource': 'Data source',
  'sourceLocal': 'On device',
  'sourceCloud': 'Cloud',
  'sourceLocalHint': 'All data stays on this device',
  'sourceCloudHint': 'Live sync with Firebase Firestore',
  'cloudUnavailable': 'Firebase is not configured in this build',

  // Vehicle paint
  'vehicleColor': 'Vehicle colour',
  'paintBlack': 'Black',
  'paintWhite': 'White',
  'paintSilver': 'Silver / Grey',
  'paintNavy': 'Navy blue',
  'paintRed': 'Red',
  'paintOlive': 'Olive green',
  'paintBronze': 'Bronze / Brown',
  'addVehicleToView': 'Add a vehicle to view',
};
