/// Arabic (default) string table.
const Map<String, String> kStringsAr = {
  // App shell
  'appTitle': 'العناية بالسيارة',
  'tabHome': 'الرئيسية',
  'tabMaintenanceLog': 'سجل الصيانة',
  'tabSchedule': 'جدول الصيانات',
  'tabFuel': 'الوقود',
  'tabExpenses': 'المصاريف',
  'tabWorkshops': 'الورش',
  'settings': 'الإعدادات',
  'language': 'اللغة',
  'themeMode': 'المظهر',
  'themeSystem': 'حسب النظام',
  'themeLight': 'فاتح',
  'themeDark': 'داكن',
  'notifications': 'التنبيهات',

  // Generic
  'save': 'حفظ',
  'cancel': 'إلغاء',
  'delete': 'حذف',
  'edit': 'تعديل',
  'add': 'إضافة',
  'search': 'بحث',
  'all': 'الكل',
  'none': 'لا يوجد',
  'today': 'اليوم',
  'date': 'التاريخ',
  'notes': 'ملاحظات',
  'optional': 'اختياري',
  'required': 'هذا الحقل مطلوب',
  'invalidNumber': 'أدخل رقمًا صحيحًا',
  'km': 'كم',
  'liter': 'لتر',
  'currency': 'ج.م',
  'perKm': 'لكل كم',
  'lPer100Km': 'ل/100كم',
  'metricLPer100Km': 'لتر / 100 كم',
  'metricKmPerLiter': 'كيلومتر / لتر',
  'fuelEconomy': 'اقتصاد الوقود',
  'currentTank': 'الخزان الحالي',
  'runningCostPerKm': 'التكلفة الجارية / كم',
  'sinceLastFill': 'منذ آخر تعبئة',
  'liveConsumption': 'لحظي',
  'settledConsumption': 'مستقر',
  'displayMetric': 'وحدة الكفاءة',
  'onThisTank': 'على هذا الخزان',
  'amortising': 'تنخفض كلما قدت',
  'ecoTips': 'القيادة الاقتصادية وتوفير الوقود',
  'ecoTipsHint': 'عادات صغيرة، لترات محسوسة',
  'ecoCatDriving': 'عادات القيادة',
  'ecoCatClimate': 'التكييف',
  'ecoCatVehicle': 'السيارة والصيانة',
  'ecoDriving1': 'انطلق بسلاسة',
  'ecoDriving1Body':
      'اضغط دواسة البنزين بهدوء بدل الانطلاق المفاجئ. التسارع العنيف قد يستهلك وقوداً أكثر بنحو الثلث على نفس المسافة.',
  'ecoDriving2': 'حافظ على سرعة ثابتة',
  'ecoDriving2Body':
      'السرعة الثابتة أوفر بكثير من التسارع والتباطؤ المتكرر. على الطرق المفتوحة أغلب السيارات أكفأ بين 80 و100 كم/س.',
  'ecoDriving3': 'فرمل مبكراً وبهدوء',
  'ecoDriving3Body':
      'راقب الطريق أمامك وارفع قدمك مبكراً. كل فرملة عنيفة تهدر سرعة دفعت وقوداً بالفعل للوصول إليها.',
  'ecoClimate1': 'صرّف هواء الكابينة أولاً',
  'ecoClimate1Body':
      'افتح النوافذ أول دقيقة لإخراج الهواء الساخن، ثم أغلقها وشغّل التكييف. الكمبروسور سيعمل بجهد أقل بكثير.',
  'ecoClimate2': 'استخدم إعادة تدوير الهواء',
  'ecoClimate2Body':
      'بعد أن تبرد الكابينة حوّل إلى وضع إعادة التدوير. تبريد هواء الداخل أرخص كثيراً من تبريد الهواء الخارجي الساخن مراراً.',
  'ecoClimate3': 'النوافذ داخل المدينة، والتكييف على الطريق السريع',
  'ecoClimate3Body':
      'تحت 60 كم/س تقريباً تكون النوافذ المفتوحة أوفر من التكييف. وفوق ذلك تصبح مقاومة الهواء أغلى من الكمبروسور.',
  'ecoVehicle1': 'افحص ضغط الإطارات شهرياً',
  'ecoVehicle1Body':
      'الإطارات الناقصة تزيد المقاومة. نقص 10% قد يكلفك نحو 2% من الوقود ويستهلك جوانب الإطار مبكراً.',
  'ecoVehicle2': 'أطفئ المحرك بدل التشغيل على الفاضي',
  'ecoVehicle2Body':
      'الوقوف بالمحرك دائراً أكثر من 30 ثانية يستهلك أكثر من إعادة التشغيل. عند إشارة طويلة أو مزلقان، أطفئ المحرك.',
  'ecoVehicle3': 'أفرغ الشنطة',
  'ecoVehicle3Body':
      'كل 50 كجم وزن زائد تكلف نحو 1% إلى 2% من الوقود. وحمّالات السقف أغلى بكثير — انزعها عند عدم الحاجة.',
  'close': 'إغلاق',
  'customItems': 'بنود أخرى',
  'viewReplacedParts': 'عرض الأجزاء المستبدلة',
  'noPartsRecorded': 'لم تُسجَّل أجزاء أو فحوصات لهذه الصيانة.',
  'partsCount': 'أجزاء',
  'exportPdfHint': 'تقرير منسّق يحتوي جداول ملخّصة ورسوم بيانية للاتجاهات.',
  'exportDataHint': 'بيانات خام للجداول الحسابية والنسخ الاحتياطية.',
  'kmPerLiter': 'كم/لتر',
  'day': 'يوم',
  'days': 'يوم',
  'month': 'شهر',
  'months': 'أشهر',
  'viewAll': 'عرض الكل',
  'confirmDelete': 'هل تريد حذف هذا العنصر؟',
  'retry': 'إعادة المحاولة',
  'somethingWentWrong': 'حدث خطأ ما',

  // Vehicles
  'vehicles': 'السيارات',
  'myVehicles': 'سياراتي',
  'addVehicle': 'إضافة سيارة',
  'editVehicle': 'تعديل السيارة',
  'make': 'الماركة',
  'model': 'الموديل',
  'year': 'سنة الصنع',
  'nickname': 'اسم مختصر',
  'plateNumber': 'رقم اللوحة',
  'initialOdometer': 'قراءة العداد الحالية',
  'currentOdometer': 'قراءة العداد',
  'updateOdometer': 'تحديث العداد',
  'purchaseDate': 'تاريخ الشراء',
  'licenseExpiry': 'انتهاء الرخصة',
  'insuranceExpiry': 'انتهاء التأمين',
  'noVehicles': 'لا توجد سيارات بعد',
  'noVehiclesHint': 'أضف سيارتك الأولى لتبدأ تتبع الصيانة والوقود',
  'switchVehicle': 'تبديل السيارة',

  // Dashboard
  'dashboard': 'لوحة التحكم',
  'totalSpend': 'إجمالي المصروفات',
  'thisMonth': 'هذا الشهر',
  'avgDaily': 'متوسط يومي',
  'avgMonthly': 'متوسط شهري',
  'alerts': 'تنبيهات',
  'noAlerts': 'كل شيء تمام، لا توجد تنبيهات',
  'consumablesHealth': 'حالة الأجزاء المستهلكة',
  'documents': 'التأمين والوثائق',
  'carInsurance': 'تأمين السيارة',
  'carLicense': 'رخصة السيارة',
  'renewsOn': 'يجدد في',
  'remainingDays': 'متبقي {n} يوم',
  'expired': 'منتهي',
  'fuelEfficiency': 'كفاءة الوقود',
  'quickActions': 'إجراءات سريعة',
  'lifespan': 'العمر الافتراضي',
  'consumed': 'تم استهلاك',
  'remaining': 'متبقي',
  'overdue': 'متأخرة',
  'dueSoon': 'قريبة',
  'healthy': 'جيدة',

  // Fuel
  'fuelLogs': 'سجل الوقود',
  'addFuelEntry': 'إضافة تعبئة وقود',
  'fuelType': 'نوع الوقود',
  'fuelAmount': 'الكمية (لتر)',
  'totalCost': 'التكلفة الإجمالية',
  'pricePerLiter': 'سعر اللتر',
  'fullTank': 'تعبئة كاملة',
  'fullTankHint': 'اختياري. التعبئة الجزئية تُحتسب أيضاً',
  'efficiency': 'الكفاءة',
  'costPerKm': 'التكلفة لكل كم',
  'distance': 'المسافة',
  'bestEfficiency': 'أفضل كفاءة',
  'avgEfficiency': 'متوسط الكفاءة',
  'octaneComparison': 'مقارنة أنواع البنزين',
  'octaneComparisonHint': 'متوسط الكفاءة والتكلفة لكل نوع وقود استخدمته',
  'noFuelLogs': 'لا يوجد سجل وقود بعد',
  'needsTwoFills': 'يحتاج تعبئة ثانية لحساب الاستهلاك',
  'octane92': 'بنزين ٩٢',
  'octane95': 'بنزين ٩٥',
  'diesel': 'سولار',
  'fuelTrend': 'تطور الكفاءة',

  // Maintenance
  'maintenance': 'الصيانة',
  'maintenanceHistory': 'سجل الصيانات',
  'logService': 'تسجيل صيانة',
  'serviceType': 'نوع الصيانة',
  'workshop': 'الورشة',
  'cost': 'التكلفة',
  'partsReplaced': 'الأجزاء المستبدلة',
  'consumableParts': 'قطع الغيار',
  'trackedDistance': 'المسافة المتتبعة',
  'costPerKmHint': 'إجمالي الإنفاق على المسافة المقطوعة منذ إضافة السيارة',
  'noDistanceYet': 'قُد المسافة لعرض التكلفة لكل كم',
  'replaceAndChange': 'تغيير و استبدال',
  'inspectAndReview': 'فحص ومراجعة',
  'majorService': 'صيانة كبرى',
  'minorService': 'صيانة صغرى',
  'importantService': 'صيانة هامة',
  'nextService': 'الصيانة القادمة',
  'estimatedDate': 'التاريخ المتوقع',
  'upcomingServices': 'الصيانات القادمة',
  'completedServices': 'الصيانات المنفذة',
  'serviceRoadmap': 'خريطة الصيانات',
  'noMaintenanceLogs': 'لا يوجد سجل صيانة بعد',
  'markDone': 'تم التنفيذ',
  'resetPart': 'تصفير الجزء',
  'resetPartHint': 'سجّل استبدال هذا الجزء عند العداد الحالي',

  // Expenses
  'expenses': 'المصاريف',
  'addExpense': 'إضافة مصروف',
  'category': 'التصنيف',
  'amount': 'المبلغ',
  'title': 'البيان',
  'noExpenses': 'لا توجد مصاريف مسجلة',
  'breakdown': 'التوزيع',
  'catRepair': 'إصلاحات',
  'catAccessories': 'إكسسوارات',
  'catParking': 'انتظار',
  'catFines': 'مخالفات',
  'catWash': 'غسيل',
  'catTolls': 'رسوم طرق',
  'catInsurance': 'تأمين',
  'catLicense': 'رخص',
  'catOther': 'أخرى',

  // Dealers & emergency
  'workshopsAndDealers': 'الورش والموزعين',
  'authorizedDealers': 'الوكلاء المعتمدون',
  'addWorkshop': 'إضافة ورشة',
  'searchDealers': 'ابحث بالاسم أو المدينة',
  'call': 'اتصال',
  'hotline': 'الخط الساخن',
  'openInMaps': 'فتح في الخرائط',
  'openingHours': 'مواعيد العمل',
  'rating': 'التقييم',
  'city': 'المدينة',
  'address': 'العنوان',
  'phone': 'الهاتف',
  'services': 'الخدمات',
  'noDealers': 'لا توجد نتائج مطابقة',
  'emergency': 'الطوارئ',
  'emergencyNumbers': 'أرقام الطوارئ',
  'safetyTips': 'إرشادات السلامة على الطريق',
  'couldNotLaunch': 'تعذر تنفيذ الإجراء على هذا الجهاز',

  // Consumable parts
  'partEngineOil': 'زيت المحرك',
  'partOilFilter': 'فلتر الزيت',
  'partAirFilter': 'فلتر هواء المحرك',
  'partCabinFilter': 'فلتر التكييف',
  'partBrakePads': 'تيل الفرامل',
  'partBrakeFluid': 'زيت الفرامل',
  'partTires': 'الإطارات (الكاوتش)',
  'partTransmissionOil': 'زيت الفتيس',
  'partPowerSteering': 'زيت الباور',
  'partCoolant': 'مياه التبريد',
  'partSparkPlugs': 'البوجيهات',
  'partBattery': 'البطارية',

  // Inspection checklist
  'checkTires': 'الإطارات وضغط الهواء',
  'checkSuspension': 'العفشة',
  'checkTightening': 'تربيط كامل',
  'checkLights': 'الإضاءة والإشارات',
  'checkRearPads': 'تيل الفرامل الخلفي',
  'checkCoolingCircuit': 'مراجعة دورة التبريد',
  'checkBattery': 'فحص البطارية',

  // Dealer kinds & services
  'kindAuthorizedService': 'مركز خدمة معتمد',
  'kindSpecializedCenter': 'مركز خدمة متخصص',
  'kindShowroom': 'معرض',
  'kindWorkshop': 'ورشة',
  'kindTireShop': 'مركز إطارات',
  'kindTowing': 'ونش وإنقاذ',
  'srvPeriodic': 'صيانة دورية',
  'srvMechanical': 'ميكانيكا',
  'srvElectrical': 'كهرباء',
  'srvBodyPaint': 'سمكرة ودهان',
  'srvSpareParts': 'قطع غيار',
  'srvSales': 'مبيعات',

  // Emergency
  'emPolice': 'الشرطة',
  'emAmbulance': 'الإسعاف',
  'emFire': 'المطافئ',
  'emTraffic': 'المرور',
  'emTourist': 'شرطة السياحة',
  'emGas': 'طوارئ الغاز',
  'emElectricity': 'طوارئ الكهرباء',

  // Safety tips
  'tipHazardLights': 'شغّل فلاشر التحذير فورًا عند التوقف الاضطراري.',
  'tipPullOverRight': 'اخرج بالسيارة إلى أقصى اليمين بعيدًا عن مسار السير.',
  'tipTriangle': 'ضع المثلث العاكس على بعد ٥٠-١٠٠ متر خلف السيارة.',
  'tipExitFromRight': 'انزل من الباب الأيمن دائمًا، لا تنزل ناحية الطريق.',
  'tipStayBehindBarrier': 'انتظر خلف الحاجز أو بعيدًا عن السيارة، لا بداخلها.',
  'tipShareLocation': 'شارك موقعك الحي مع شخص تثق به قبل طلب المساعدة.',
  'tipKeepKit': 'احتفظ دائمًا بمثلث، إسطبانة، كابل بطارية وطفاية حريق.',

  // Extra UI
  'addFirstEntry': 'ابدأ بإضافة أول عملية',
  'partialFill': 'تعبئة جزئية',
  'estimated': 'تقديري',
  'basedOnYourDriving': 'بناءً على متوسط قيادتك',
  'notEnoughData': 'لا توجد بيانات كافية بعد',
  'litersShort': 'ل',
  'perLiter': 'للتر',
  'segmentSince': 'منذ آخر تعبئة كاملة',
  'daysShort': 'ي',
  'noSchedule': 'أضف قراءة العداد لعرض الجدول',
  'kmRemainingLabel': 'باقي {n} كم',
  'kmOverdueLabel': 'متأخرة بـ {n} كم',
  'serviceAt': 'عند {n} كم',
  'monthsLabel': '{n} شهر',
  'done': 'تمت',
  'vsAverage': 'مقارنة بالمتوسط',
  'better': 'أفضل',
  'worse': 'أقل',
  'addNote': 'أضف ملاحظة',
  'chooseParts': 'اختر الأجزاء التي تم تغييرها',
  'stationName': 'اسم المحطة',
  'rateThisPlace': 'قيّم هذا المكان',
  'thanksForRating': 'شكرًا لتقييمك',
  'deleted': 'تم الحذف',
  'saved': 'تم الحفظ',

  // Alerts & notifications
  'alertServiceOverdue': 'صيانة {km} كم متأخرة',
  'alertServiceDueSoon': 'اقتربت صيانة {km} كم',
  'alertPartOverdue': '{part} تجاوز عمره الافتراضي',
  'alertPartDueSoon': '{part} يحتاج استبدال قريبًا',
  'alertLicenseExpired': 'رخصة السيارة منتهية',
  'alertLicenseExpiring': 'رخصة السيارة تنتهي خلال {n} يوم',
  'alertInsuranceExpired': 'تأمين السيارة منتهي',
  'alertInsuranceExpiring': 'تأمين السيارة ينتهي خلال {n} يوم',
  'alertOdometerStale': 'حدّث قراءة العداد',
  'alertOdometerStaleDetail':
      'آخر تحديث من {n} يوم — التحديث يحسّن دقة التوقعات',
  'notifServiceTitle': 'موعد صيانة قادم',
  'notifPartTitle': 'جزء يحتاج استبدال',
  'notifDocumentTitle': 'تجديد وثيقة',

  // Analytics & export
  'analytics': 'التحليلات',
  'dateRange': 'الفترة الزمنية',
  'rangeLast3Months': '٣ أشهر',
  'rangeLast6Months': '٦ أشهر',
  'rangeLastYear': 'سنة',
  'rangeAllTime': 'كل الفترات',
  'customRange': 'فترة مخصصة',
  'exportReport': 'تصدير التقرير',
  'exportFormat': 'صيغة الملف',
  'exportNow': 'تصدير الآن',
  'exportSavedTo': 'تم الحفظ في',
  'exportDownloaded': 'بدأ تنزيل الملف',
  'exportFailed': 'تعذر تصدير التقرير',
  'entries': 'عدد العمليات',
  'reportSummary': 'ملخص التقرير',
  'totalDistance': 'إجمالي المسافة',
  'totalLiters': 'إجمالي اللترات',

  // Maintenance engine
  'firstCheckService': 'فحص أول (تشغيل)',
  'nextServiceDue': 'موعد الصيانة القادمة',
  'sinceLastService': 'منذ آخر صيانة',
  'basedOnLastService': 'محسوبة من آخر صيانة عند {n} كم',
  'noServiceYet': 'لم تسجل أي صيانة بعد',
  'dueByDistance': 'حسب المسافة',
  'dueByTime': 'حسب المدة',
  'firstCheckHint': 'أول ١٠٠٠ كم أو بعد شهر من الاستلام',

  // Backend
  'dataSource': 'مصدر البيانات',
  'sourceLocal': 'محلي',
  'sourceCloud': 'سحابي',
  'sourceLocalHint': 'كل البيانات محفوظة على الجهاز فقط',
  'sourceCloudHint': 'مزامنة حية مع Firebase Firestore',
  'cloudUnavailable': 'Firebase غير مهيأ على هذا التطبيق',

  // Vehicle paint
  'vehicleColor': 'لون السيارة',
  'paintBlack': 'أسود',
  'paintWhite': 'أبيض',
  'paintSilver': 'فضي / رمادي',
  'paintNavy': 'كحلي',
  'paintRed': 'أحمر',
  'paintOlive': 'زيتي',
  'paintBronze': 'برونزي / بني',
  'addVehicleToView': 'أضف سيارة للعرض',

  // Vehicle photo
  'vehiclePhoto': 'صورة السيارة',
  'takePhoto': 'التقاط صورة',
  'chooseFromGallery': 'اختيار من المعرض',
  'uploadImage': 'رفع صورة',
  'removePhoto': 'إزالة الصورة',
  'imageTooLarge': 'الصورة كبيرة جدًا، اختر صورة أصغر',

  // Schedule & pricing
  'partFuelFilter': 'فلتر البنزين',
  'partDrainPlugGasket': 'جوان مسمار الزيت',
  'partTransmissionFilter': 'فلتر الفتيس',
  'partTimingBelt': 'سير الكاتينة والشداد',
  'partDriveBelt': 'سير الماكينة',
  'itemCleanerSupplies': 'مواد تنظيف ومستلزمات',
  'checkFluidLevels': 'فحص مستويات السوائل',
  'checkChassisScan': 'فحص عام للشاسيه',
  'checkLeaks': 'فحص التسريبات',
  'freeService': 'مجانية',
  'estimatedCost': 'التكلفة التقديرية',
  'priceSettings': 'إعدادات الأسعار',
  'priceMultiplier': 'معامل الأسعار',
  'priceMultiplierHint': 'اضبط الأسعار حسب أسعار السوق لديك',
  'customPrice': 'سعر مخصص',
  'resetPrices': 'إعادة الأسعار الافتراضية',
  'optionalExtras': 'إضافات اختيارية',
  'labourCost': 'المصنعية',
  'priceRangeNote': 'تقديري — قد يختلف حسب الورشة',
};
