/// English string table. Also acts as the fallback for missing translations.
const Map<String, String> kStringsEn = {
  // App shell
  'appTitle': 'Vehicle Care',
  'tabHome': 'Home',
  'tabMaintenanceLog': 'Service Log',
  'tabSchedule': 'Schedule',
  'tabFuel': 'Fuel',
  'tabExpenses': 'Expenses',
  'tabWorkshops': 'Workshops',
  'settings': 'Settings',
  'language': 'Language',
  'themeMode': 'Appearance',
  'themeSystem': 'System',
  'themeLight': 'Light',
  'themeDark': 'Dark',
  'notifications': 'Notifications',

  // Generic
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'edit': 'Edit',
  'add': 'Add',
  'search': 'Search',
  'all': 'All',
  'none': 'None',
  'today': 'Today',
  'date': 'Date',
  'notes': 'Notes',
  'optional': 'optional',
  'required': 'This field is required',
  'invalidNumber': 'Enter a valid number',
  'km': 'km',
  'liter': 'L',
  'cubicMeter': 'm³',
  'currency': 'EGP',
  'perKm': 'per km',
  'lPer100Km': 'L/100km',
  'metricLPer100Km': 'Litres / 100 km',
  'metricKmPerLiter': 'Kilometres / litre',
  'fuelEconomy': 'Fuel economy',
  'currentTank': 'Current tank',
  'runningCostPerKm': 'Running cost / km',
  'sinceLastFill': 'Since last fill-up',
  'liveConsumption': 'Live',
  'settledConsumption': 'Settled',
  'displayMetric': 'Efficiency unit',
  'defaultFuelPrice': 'Default price per litre',
  'defaultFuelPriceHint': 'Pre-filled for this fuel type on a new entry',
  'onThisTank': 'On this tank',
  'amortising': 'Falls as you drive',
  'ecoTips': 'Eco-driving & fuel saving',
  'ecoTipsHint': 'Small habits, measurable litres',
  'ecoCatDriving': 'Driving habits',
  'ecoCatClimate': 'Air conditioning',
  'ecoCatVehicle': 'Vehicle & maintenance',
  'ecoDriving1': 'Accelerate smoothly',
  'ecoDriving1Body':
      'Ease onto the throttle instead of launching. Hard acceleration can burn up to a third more fuel over the same stretch of road.',
  'ecoDriving2': 'Hold a steady cruise',
  'ecoDriving2Body':
      'A constant speed uses far less fuel than surging and slowing. On open roads, most cars are most efficient between 80 and 100 km/h.',
  'ecoDriving3': 'Brake early, brake gently',
  'ecoDriving3Body':
      'Read the traffic ahead and lift off early. Every hard stop throws away speed you already paid fuel to build.',
  'ecoClimate1': 'Vent the cabin first',
  'ecoClimate1Body':
      'Open the windows for the first minute to push hot air out, then close them and switch the AC on. The compressor works far less.',
  'ecoClimate2': 'Use recirculation',
  'ecoClimate2Body':
      'Once the cabin is cool, switch to recirculate. Re-cooling inside air costs much less than chilling hot outside air over and over.',
  'ecoClimate3': 'Windows in town, AC on the highway',
  'ecoClimate3Body':
      'Below about 60 km/h open windows are cheaper than AC. Above that, the extra drag costs more than the compressor does.',
  'ecoVehicle1': 'Check tyre pressure monthly',
  'ecoVehicle1Body':
      'Under-inflated tyres drag. Ten percent low can cost around two percent in fuel, and wears the shoulders out early.',
  'ecoVehicle2': 'Switch off rather than idle',
  'ecoVehicle2Body':
      'Idling longer than about 30 seconds burns more than restarting does. At a long light or a level crossing, turn the engine off.',
  'ecoVehicle3': 'Empty the boot',
  'ecoVehicle3Body':
      'Every 50 kg of dead weight costs roughly one to two percent in fuel. Roof racks and boxes cost far more — take them off when not in use.',
  'close': 'Close',
  'pressBackToExit': 'Press back again to exit',
  'customItems': 'Other items',
  'viewReplacedParts': 'View replaced parts',
  'noPartsRecorded': 'No parts or checks were recorded for this service.',
  'partsCount': 'parts',
  'exportPdfHint': 'A formatted report with summary tables and trend charts.',
  'exportDataHint': 'Raw data for spreadsheets and backups.',
  'allPartsHealthy': 'All parts healthy',
  'initialOdometerHint':
      'The reading the car joined the app at. Every cost-per-km figure is measured from it.',
  'initialAboveCurrent': 'Cannot be higher than the current reading',
  'editFuelEntry': 'Edit fuel entry',
  'editService': 'Edit service',
  'editExpense': 'Edit expense',
  'editWorkshop': 'Edit workshop',
  'saveChanges': 'Save changes',
  'currentOdometerHint': 'Must be at least the initial reading',
  'odometerRequired': 'Required',
  'fuelEmergency': 'Out of fuel',
  'fuelEmergencyHint': 'What to do when the tank runs dry',
  'fuelEmgCatSafety': 'Make the car safe',
  'fuelEmgCatEngine': 'Protect the engine',
  'fuelEmgCatRefuel': 'Refuelling',
  'fuelEmg1': 'Coast to the shoulder',
  'fuelEmg1Body':
      'The moment the engine falters, use the momentum you still have to reach the hard shoulder. Steering and brakes get heavy once the engine stops, so commit early rather than drifting to a halt in a live lane.',
  'fuelEmg2': 'Hazards on immediately',
  'fuelEmg2Body':
      'Switch the hazard lights on before you stop, not after. At night or in rain, turn the side lights on too so the car is visible from a distance.',
  'fuelEmg3': 'Place the warning triangle',
  'fuelEmg3Body':
      'Set the reflective triangle well behind the car, further on a fast road, and wear a high-visibility vest. Wait behind the barrier, never inside the car on the shoulder of a motorway.',
  'fuelEmg4': 'Stop cranking the starter',
  'fuelEmg4Body':
      'Repeated attempts on a dry tank overheat the starter motor and can burn it out. Two short tries are enough to confirm the problem.',
  'fuelEmg5': 'Do not run the pump dry',
  'fuelEmg5Body':
      'The fuel pump is cooled and lubricated by the fuel around it. Turn the ignition off and leave it off. Running dry is what kills pumps, not the empty tank itself.',
  'fuelEmg6': 'Diesel needs bleeding',
  'fuelEmg6Body':
      'A diesel that has run dry usually draws air into the lines and will not restart on fuel alone. Expect to prime or bleed the system, and call a technician if there is no manual primer.',
  'fuelEmg7': 'Use an approved container only',
  'fuelEmg7Body':
      'Buy a certified metal or plastic fuel can. Never use a water bottle or an oil jug: they melt, leak and build static. Fill it on the ground, never in the boot or on a plastic surface.',
  'fuelEmg8': 'Check the grade before you pour',
  'fuelEmg8Body':
      'Confirm the octane your car takes, or that it is diesel, before filling the can. A wrong fill costs far more than the tow you were trying to avoid. If in doubt, do not start the engine, call for help.',
  'fuelEmg9': 'Add enough, then restart properly',
  'fuelEmg9Body':
      'Five to ten litres is enough to reach a station. Turn the ignition to ON for a few seconds without cranking so the pump primes, then start. Refill fully at the first station and do not run low again.',
  'fuelGuidelines': 'Fuel consumption & efficiency',
  'fuelGuidelinesHint': 'Spend less, and spot when something is wrong',
  'fuelGuideCatDriving': 'Driving habits',
  'fuelGuideCatMaintenance': 'Maintenance checks',
  'fuelGuideCatLoad': 'Drag & load',
  'fuelGuide1': 'Accelerate smoothly',
  'fuelGuide1Body':
      'Ease onto the throttle instead of launching. Hard acceleration can burn up to a third more fuel over the same stretch of road.',
  'fuelGuide2': 'Hold a steady cruise',
  'fuelGuide2Body':
      'A constant speed uses far less fuel than surging and slowing. On open roads most cars are most efficient between 80 and 100 km/h.',
  'fuelGuide3': 'Use engine braking',
  'fuelGuide3Body':
      'Lift off early and let the car slow in gear. Modern injection cuts fuel completely on a trailing throttle, so coasting in gear costs nothing while idling in neutral still burns fuel.',
  'fuelGuide4': 'Check tyre pressure monthly',
  'fuelGuide4Body':
      'Under-inflated tyres drag. Ten percent low can cost around two percent in fuel and wears the shoulders out early.',
  'fuelGuide5': 'Replace clogged filters',
  'fuelGuide5Body':
      'A blocked air filter starves the engine and a tired fuel filter makes the pump work harder. Both show up as a gradual, unexplained rise in consumption.',
  'fuelGuide6': 'Inspect plugs and injectors',
  'fuelGuide6Body':
      'Worn spark plugs and dirty injectors burn fuel without turning it into motion. A sudden jump in consumption with rough idling or hesitation points here first.',
  'fuelGuide7': 'Empty the boot',
  'fuelGuide7Body':
      'Every 50 kg of dead weight costs roughly one to two percent in fuel. Clear out what has been living in there for months.',
  'fuelGuide8': 'Take the roof rack off',
  'fuelGuide8Body':
      'An empty roof rack or box can cost over ten percent on the motorway. Remove it the day the trip ends, not the next time you need it.',
  'fuelGuide9': 'Close the windows at speed',
  'fuelGuide9Body':
      'Above about 60 km/h open windows cost more in drag than the air conditioning costs to run. Below that, the windows are the cheaper option.',
  'appTagline': 'Every service, every litre, every kilometre',
  'splashPreparing': 'Getting your garage ready',
  'notifServiceKmTitle': 'Service almost due',
  'alertServiceKmRemaining': '{km} km service · {remaining} km to go',
  'alertPartKmRemaining': '{part} · {remaining} km to go',
  'kmPerLiter': 'km/L',
  'day': 'day',
  'days': 'days',
  'month': 'month',
  'months': 'months',
  'viewAll': 'View all',
  'confirmDelete': 'Delete this entry?',
  'retry': 'Retry',
  'somethingWentWrong': 'Something went wrong',

  // Vehicles
  'vehicles': 'Vehicles',
  'myVehicles': 'My vehicles',
  'addVehicle': 'Add vehicle',
  'editVehicle': 'Edit vehicle',
  'make': 'Make',
  'model': 'Model',
  'year': 'Year',
  'nickname': 'Nickname',
  'plateNumber': 'Plate number',
  'otherOption': 'Other',
  'searchCatalog': 'Search',
  'noCatalogMatches': 'No matching results',
  'selectMakeFirst': 'Pick a make first',
  'customMake': 'Custom make',
  'customModel': 'Custom model',
  'tankCapacity': 'Tank size',
  'initialOdometer': 'Initial odometer',
  'currentOdometer': 'Odometer',
  'vehicleCurrentOdometer': 'Current odometer',
  'updateOdometer': 'Update odometer',
  'purchaseDate': 'Purchase date',
  'licenseExpiry': 'License expiry',
  'insuranceExpiry': 'Insurance expiry',
  'noVehicles': 'No vehicles yet',
  'noVehiclesHint': 'Add your first vehicle to start tracking fuel and service',
  'switchVehicle': 'Switch vehicle',

  // Dashboard
  'dashboard': 'Dashboard',
  'totalSpend': 'Total spend',
  'thisMonth': 'This month',
  'avgDaily': 'Daily average',
  'avgMonthly': 'Monthly average',
  'alerts': 'Alerts',
  'noAlerts': 'All good — nothing needs attention',
  'consumablesHealth': 'Consumable parts health',
  'documents': 'Insurance & documents',
  'carInsurance': 'Car insurance',
  'carLicense': 'Car license',
  'renewsOn': 'Renews on',
  'remainingDays': '{n} days left',
  'expired': 'Expired',
  'fuelEfficiency': 'Fuel efficiency',
  'quickActions': 'Quick actions',
  'lifespan': 'Rated life',
  'consumed': 'Used',
  'remaining': 'left',
  'overdue': 'Overdue',
  'dueSoon': 'Due soon',
  'healthy': 'Healthy',

  // Fuel
  'fuelLogs': 'Fuel logs',
  'addFuelEntry': 'Add fuel entry',
  'fuelType': 'Fuel type',
  'fuelAmount': 'Amount (L)',
  'fuelAmountGas': 'Amount (m³)',
  'totalCost': 'Total cost',
  'pricePerLiter': 'Price per litre',
  'pricePerCubicMeter': 'Price per m³',
  'fullTank': 'Full tank',
  'fullTankHint': 'Optional. Partial fills are measured too',
  'efficiency': 'Efficiency',
  'costPerKm': 'Cost per km',
  'distance': 'Distance',
  'bestEfficiency': 'Best efficiency',
  'avgEfficiency': 'Average efficiency',
  'octaneComparison': 'Octane comparison',
  'octaneComparisonHint': 'Average efficiency and cost for each fuel you used',
  'noFuelLogs': 'No fuel entries yet',
  'needsTwoFills': 'Needs a second fill to compute consumption',
  'octane80': 'Octane 80',
  'octane92': 'Octane 92',
  'octane95': 'Octane 95',
  'diesel': 'Diesel',
  'naturalGas': 'Natural gas (CNG)',
  'fuelTrend': 'Efficiency trend',

  // Maintenance
  'maintenance': 'Maintenance',
  'maintenanceHistory': 'Service history',
  'logService': 'Log a service',
  'serviceType': 'Service type',
  'workshop': 'Workshop',
  'cost': 'Cost',
  'partsReplaced': 'Parts replaced',
  'consumableParts': 'Parts',
  'trackedDistance': 'Tracked distance',
  'costPerKmHint':
      'Total spend over the distance driven since this vehicle joined',
  'noDistanceYet': 'Drive to see cost per km',
  'replaceAndChange': 'Replace & change',
  'inspectAndReview': 'Inspect & review',
  'majorService': 'Major service',
  'minorService': 'Minor service',
  'importantService': 'Important service',
  'nextService': 'Next service',
  'estimatedDate': 'Estimated date',
  'upcomingServices': 'Upcoming services',
  'completedServices': 'Completed services',
  'serviceRoadmap': 'Service roadmap',
  'noMaintenanceLogs': 'No service history yet',
  'markDone': 'Mark as done',
  'resetPart': 'Reset part',
  'resetPartHint': 'Record this part as replaced at the current odometer',

  // Expenses
  'expenses': 'Expenses',
  'addExpense': 'Add expense',
  'category': 'Category',
  'amount': 'Amount',
  'title': 'Title',
  'noExpenses': 'No expenses logged',
  'breakdown': 'Breakdown',
  'catRepair': 'Repairs',
  'catAccessories': 'Accessories',
  'catParking': 'Parking',
  'catFines': 'Fines',
  'catWash': 'Car wash',
  'catTolls': 'Tolls',
  'catInsurance': 'Insurance',
  'catLicense': 'License',
  'catOther': 'Other',

  // Dealers & emergency
  'workshopsAndDealers': 'Workshops & dealers',
  'authorizedDealers': 'Authorized dealers',
  'addWorkshop': 'Add workshop',
  'searchDealers': 'Search by name or city',
  'call': 'Call',
  'hotline': 'Hotline',
  'openInMaps': 'Open in Maps',
  'openingHours': 'Opening hours',
  'rating': 'Rating',
  'city': 'City',
  'address': 'Address',
  'phone': 'Phone',
  'services': 'Services',
  'noDealers': 'No matching results',
  'emergency': 'Emergency',
  'emergencyNumbers': 'Emergency numbers',
  'safetyTips': 'Roadside safety tips',
  'couldNotLaunch': 'Could not perform this action on your device',

  // Consumable parts
  'partEngineOil': 'Engine oil',
  'partOilFilter': 'Oil filter',
  'partAirFilter': 'Engine air filter',
  'partCabinFilter': 'Cabin / AC filter',
  'partBrakePads': 'Brake pads',
  'partBrakeFluid': 'Brake fluid',
  'partTires': 'Tires',
  'partTransmissionOil': 'Transmission oil',
  'partPowerSteering': 'Power steering fluid',
  'partCoolant': 'Coolant',
  'partSparkPlugs': 'Spark plugs',
  'partBattery': 'Battery',

  // Inspection checklist
  'checkTires': 'Tires and pressure',
  'checkSuspension': 'Suspension',
  'checkTightening': 'Full tightening',
  'checkLights': 'Lights and indicators',
  'checkRearPads': 'Rear brake pads',
  'checkCoolingCircuit': 'Cooling circuit',
  'checkBattery': 'Battery check',

  // Dealer kinds & services
  'kindAuthorizedService': 'Authorized service centre',
  'kindSpecializedCenter': 'Specialized service centre',
  'kindShowroom': 'Showroom',
  'kindWorkshop': 'Workshop',
  'kindTireShop': 'Tire centre',
  'kindTowing': 'Towing & recovery',
  'srvPeriodic': 'Periodic service',
  'srvMechanical': 'Mechanical',
  'srvElectrical': 'Electrical',
  'srvBodyPaint': 'Body & paint',
  'srvSpareParts': 'Spare parts',
  'srvSales': 'Sales',

  // Emergency
  'emPolice': 'Police',
  'emAmbulance': 'Ambulance',
  'emFire': 'Fire brigade',
  'emTraffic': 'Traffic police',
  'emTourist': 'Tourist police',
  'emGas': 'Gas emergency',
  'emElectricity': 'Electricity emergency',

  // Safety tips
  'tipHazardLights': 'Switch on hazard lights the moment you stop.',
  'tipPullOverRight': 'Pull as far right as possible, clear of moving traffic.',
  'tipTriangle': 'Place the warning triangle 50-100 m behind the car.',
  'tipExitFromRight':
      'Always leave through the right-hand door, never towards traffic.',
  'tipStayBehindBarrier':
      'Wait behind the barrier, away from the car — not inside it.',
  'tipShareLocation':
      'Share your live location with someone you trust before calling for help.',
  'tipKeepKit':
      'Keep a triangle, spare wheel, jump leads and an extinguisher on board.',

  // Extra UI
  'addFirstEntry': 'Add your first entry to get started',
  'partialFill': 'Partial fill',
  'estimated': 'Estimated',
  'basedOnYourDriving': 'Based on your driving average',
  'notEnoughData': 'Not enough data yet',
  'litersShort': 'L',
  'perLiter': 'per litre',
  'segmentSince': 'since last full tank',
  'daysShort': 'd',
  'noSchedule': 'Add an odometer reading to see the schedule',
  'kmRemainingLabel': '{n} km to go',
  'kmOverdueLabel': '{n} km overdue',
  'serviceAt': 'at {n} km',
  'monthsLabel': '{n} months',
  'done': 'Done',
  'vsAverage': 'vs average',
  'better': 'better',
  'worse': 'lower',
  'addNote': 'Add a note',
  'chooseParts': 'Select the parts that were replaced',
  'stationName': 'Station name',
  'rateThisPlace': 'Rate this place',
  'thanksForRating': 'Thanks for rating',
  'deleted': 'Deleted',
  'saved': 'Saved',

  // Alerts & notifications
  'alertServiceOverdue': '{km} km service is overdue',
  'alertServiceDueSoon': '{km} km service is coming up',
  'alertPartOverdue': '{part} has passed its rated life',
  'alertPartDueSoon': '{part} needs replacing soon',
  'alertLicenseExpired': 'Car license has expired',
  'alertLicenseExpiring': 'Car license expires in {n} days',
  'alertInsuranceExpired': 'Car insurance has expired',
  'alertInsuranceExpiring': 'Car insurance expires in {n} days',
  'alertOdometerStale': 'Update your odometer',
  'alertOdometerStaleDetail':
      'Last updated {n} days ago — updating sharpens every projection',
  'notifServiceTitle': 'Service coming up',
  'notifPartTitle': 'Part needs replacing',
  'notifDocumentTitle': 'Document renewal',

  // Analytics & export
  'analytics': 'Analytics',
  'dateRange': 'Date range',
  'rangeLast3Months': '3 months',
  'rangeLast6Months': '6 months',
  'rangeLastYear': '1 year',
  'rangeAllTime': 'All time',
  'customRange': 'Custom range',
  'exportReport': 'Export report',
  'exportFormat': 'File format',
  'exportNow': 'Export now',
  'exportSavedTo': 'Saved to',
  'exportDownloaded': 'Download started',
  'exportFailed': 'Could not export the report',
  'entries': 'Entries',
  'reportSummary': 'Report summary',
  'totalDistance': 'Total distance',
  'totalLiters': 'Total litres',

  // Vehicle backup — one file per vehicle, carrying its whole history
  'vehicleTransfer': 'Vehicle backup',
  'vehicleTransferHint':
      'A backup file holds one vehicle with its services, fuel, expenses and '
      'renewal dates. Importing adds it as a new vehicle and never '
      'overwrites an existing one.',
  'exportVehicle': 'Export vehicle',
  'importVehicle': 'Import vehicle file',
  'vehicleExportFailed': 'Could not export this vehicle',
  'vehicleImported': 'Imported {name} · {n} entries',
  'importFailed': 'Could not import this file',
  'importWrongFormat': 'That file is not a vehicle backup',
  'importUnsupportedVersion':
      'That backup was made by a newer version of the app',

  // Maintenance engine
  'firstCheckService': 'First (run-in) check',
  'nextServiceDue': 'Next service due',
  'sinceLastService': 'since last service',
  'basedOnLastService': 'Based on your last service at {n} km',
  'noServiceYet': 'No service logged yet',
  'dueByDistance': 'by distance',
  'dueByTime': 'by time',
  'firstCheckHint': 'First 1,000 km or one month after delivery',

  // Backend
  'dataSource': 'Data source',
  'sourceLocal': 'On device',
  'sourceCloud': 'Cloud',
  'sourceLocalHint': 'All data stays on this device',
  'sourceCloudHint': 'Live sync with cloud backup',
  'cloudUnavailable': 'Cloud synchronization is currently unavailable',

  // Vehicle paint
  'vehicleColor': 'Vehicle colour',
  'paintBlack': 'Black',
  'paintWhite': 'White',
  'paintSilver': 'Silver / Grey',
  'paintNavy': 'Navy blue',
  'paintRed': 'Red',
  'paintOlive': 'Olive green',
  'paintBronze': 'Bronze / Brown',
  'addVehicleToView': 'Add a vehicle to view',

  // Vehicle photo
  'vehiclePhoto': 'Vehicle photo',
  'takePhoto': 'Take a photo',
  'chooseFromGallery': 'Choose from gallery',
  'uploadImage': 'Upload image',
  'removePhoto': 'Remove photo',
  'imageTooLarge': 'Image is too large, pick a smaller one',

  // Schedule & pricing
  'partFuelFilter': 'Fuel filter',
  'partDrainPlugGasket': 'Drain plug gasket',
  'partTransmissionFilter': 'Transmission filter',
  'partTimingBelt': 'Timing belt & tensioner',
  'partDriveBelt': 'Drive (auxiliary) belt',
  'itemCleanerSupplies': 'Cleaners & supplies',
  'checkFluidLevels': 'Fluid level check',
  'checkChassisScan': 'General chassis scan',
  'checkLeaks': 'Leak inspection',
  'freeService': 'Free',
  'estimatedCost': 'Estimated cost',
  'priceSettings': 'Price settings',
  'priceMultiplier': 'Price multiplier',
  'priceMultiplierHint': 'Scale prices to your local market rates',
  'customPrice': 'Custom price',
  'resetPrices': 'Reset to defaults',
  'optionalExtras': 'Optional extras',
  'labourCost': 'Labour',
  'priceRangeNote': 'Estimate — varies by workshop',

  // Predictive forecast
  'forecastTitle': 'Forecast',
  'forecastNeedDataTitle': 'Not enough history yet',
  'forecastNeedDataHint':
      'Log at least two odometer or fuel entries so daily mileage can be measured.',
  'forecastHabits': 'Driving habits',
  'forecastAvgDaily': 'Average daily distance',
  'forecastPerDay': 'day',
  'forecastMonthlyKm': 'Projected monthly mileage',
  'forecastYearlyKm': 'Projected yearly mileage',
  'forecastDates': 'Predicted service dates',
  'forecastNoUpcoming': 'No upcoming services to date from this pace.',
  'forecastSpend': 'Expense & fuel forecast',
  'forecastTotal': 'Total projected spend',
  'parkingTitle': 'Parking spot',
  'parkingSave': 'Save my spot',
  'parkingUpdate': 'Update details',
  'parkingSaved': 'Parking spot saved',
  'parkingCleared': 'Parking spot cleared',
  'parkingFound': 'I found my car',
  'parkingDirections': 'Directions to my car',
  'parkingFloorLabel': 'Floor / zone / bay',
  'parkingFloorHint': 'Roxy garage - level -2, bay B14',
  'parkingNoteLabel': 'Note',
  'parkingNoteHint': 'Next to the lift, blue pillar',
  'parkingEmptyHint': 'Pin where you parked so you can find the car later.',
  'parkingParkedAt': 'Parked at',
  'parkingLocating': 'Finding your location…',
  'parkingNoFix': 'No GPS fix yet — the details you wrote are still saved.',
  'parkingErrService':
      'Location is switched off on this device. Turn it on and try again.',
  'parkingErrDenied': 'The app needs location permission to pin your spot.',
  'parkingErrForever':
      'Location permission is blocked. Open settings to allow it.',
  'parkingErrUnavailable':
      'Could not get a location. Try again in the open air.',
  'parkingOpenSettings': 'Open settings',
  'or': 'or',
  'authTitle': 'Your account',
  'authSubtitle': 'Sign in to keep your history on every device.',
  'authSignIn': 'Sign in',
  'authSignUp': 'Create account',
  'authSignOut': 'Sign out',
  'authGoogle': 'Continue with Google',
  'authSkip': 'Continue without an account',
  'authEmail': 'Email',
  'authPassword': 'Password',
  'authName': 'Name',
  'authHaveAccount': 'Already have an account? Sign in',
  'authNeedAccount': "Don't have an account? Create one",
  'authForgot': 'Forgot your password?',
  'authResetSent': 'Password reset email sent',
  'authLocalOnly': 'Working on this device only',
  'authLocalOnlyHint':
      'Your data is saved here. Sign in to back it up and reach it from '
      'another device.',
  'authSignedInAs': 'Signed in as',
  'authAnonymous': 'Guest account',
  'authAnonymousHint':
      'Your data syncs, but you will lose it if the app is reinstalled. Add '
      'an email to keep it.',
  'authSignOutConfirm': 'Sign out? Your cloud data stays in your account.',
  'authErrInvalidEmail': 'That email address does not look right.',
  'authErrWrongPassword': 'Wrong email or password.',
  'authErrUserNotFound': 'No account found for that email.',
  'authErrEmailInUse': 'An account already uses that email.',
  'authErrWeakPassword': 'Choose a longer password — at least 6 characters.',
  'authErrNetwork': 'No connection. Try again when you are back online.',
  'authErrNotConfigured': 'Cloud sync is not set up in this build.',
  'authErrUnknown': 'Could not sign you in. Try again.',
  'syncMigrating': 'Moving your data to your account…',
  'syncMigrated': 'Your data is now in your account',
  'syncMigrateFailed':
      'Could not upload everything. It is still on this device.',
  'syncMerged': 'Added {n} records from this device to your account',
  'syncNothingNew': 'Your account is up to date',
  'syncConflicts':
      '{n} records differ between this device and your account. The account '
      'version was kept.',
  'syncCloudOn': 'Synced to your account',
  'syncCloudOff': 'On this device only',
  'reportTitle': 'Vehicle report',
  'reportTrackedDistance': 'Tracked distance',
  'reportFuelCost': 'Fuel cost',
  'reportServiceCost': 'Service cost',
  'reportPartsCost': 'Parts cost',
  'reportOtherCost': 'Other cost',
  'reportTotalCost': 'Total cost',
  'reportLitres': 'Litres',
  'reportConsumption': 'Consumption L/100km',
  'reportEfficiency': 'Efficiency km/L',
  'reportFuelCostPerKm': 'Fuel cost per km',
  'reportCostPerKm': 'Total cost per km',
  'reportGenerated': 'Generated',
  'reportParts': 'Parts',
  'reportOther': 'Other',
  'reportMetric': 'Metric',
  'reportValue': 'Value',
  'reportType': 'Type',
  'reportCategory': 'Category',
  'reportDescription': 'Description',
  'reportOdometer': 'Odometer',
  'reportQuantity': 'Qty',
  'reportSpendBreakdown': 'Where the money went',
  'reportConsumptionTrend': 'Fuel consumption trend',
  'reportCostTrend': 'Cost per kilometre trend',
  'reportTransactions': 'Transactions',
  'reportForecast': 'Spending & fuel forecast',
  'reportPerMonth': 'Per month',
  'reportPerYear': 'Per year',
  'reportDailyPace': 'Average daily distance',
  'reportProjectedDistance': 'Projected distance',
  'reportAmortisedNote':
      'Insurance and licensing are spread over the months each renewal covers, '
      'not charged in the month they are paid.',
  'reportPage': 'Page {n} of {total}',
  'reportRowFuel': 'Fuel',
  'reportRowService': 'Service',
  'reportRowExpense': 'Expense',
  'forecastPolicies': 'Insurance & licensing',
  'forecastPoliciesHint': 'Spread over the months each renewal covers',
  'forecastPerMonth': 'month',
  'forecastPerYear': 'year',
  'forecastGauges': 'Part remaining life',
  'forecastNoParts': 'No wear items to project yet.',
};
